spring:
  application:
  name: demoService-provider-sdutent
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/demo2?serverTimezone=UTC
#    username: root
#    password: 123456


  cloud:
    compatibility:
      verifier:
        enabled: false
server:
  port : 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true
    healthcheck:
      enabled: true
feign:
  client:
    default:
      connect-timeout: 10000
      read-timeout: 10000
